from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('items/', views.view_items, name='view_items'),
    path('items/pdf/', views.view_items_pdf, name='view_items_pdf'),
    path('add/item/', views.add_product_global, name='add_product_global'),
    path('add/rack/', views.add_rack_global, name='add_rack_global'),
    path('issue-requests/', views.issue_requests, name='issue_requests'),
    path('issue-requests/approve/<int:pk>/', views.issue_request_approve, name='issue_request_approve'),
    path('issue-requests/reject/<int:pk>/', views.issue_request_reject, name='issue_request_reject'),
    path('issue-requests/issue/<int:pk>/', views.issue_request_issue, name='issue_request_issue'),
    path('notifications/', views.notifications_center, name='notifications'),
    path('notifications/mark-read/<int:pk>/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/mark-all-read/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('my-history/', views.my_history, name='my_history'),
    path('item-requests/history/', views.item_requests_history, name='item_requests_history'),
    path('item-requests/history/pdf/', views.item_requests_history_pdf, name='item_requests_history_pdf'),
    path('upload-requests/', views.management_upload_requests, name='management_upload_requests'),
    path('upload-requests/fulfill/<int:pk>/', views.management_upload_request_fulfill, name='management_upload_request_fulfill'),
    path('upload-requests/disclose/<int:pk>/', views.management_upload_request_disclose, name='management_upload_request_disclose'),
    path('upload-requests/pdf/', views.management_upload_requests_pdf, name='management_upload_requests_pdf'),
    path('category/<slug:category>/', views.category_detail, name='category_detail'),
    # legacy issuing routes (now handled via /issue-requests/)
    path('api/category/<slug:category>/product/<str:asset_id>/', views.get_product_details, name='get_product_details'),
    path('api/user-by-username/', views.get_user_by_username, name='get_user_by_username'),
    path('category/<slug:category>/upload/', views.upload_items, name='upload_items'),
    path('category/<slug:category>/upload-history/', views.upload_history, name='upload_history'),
    path('category/<slug:category>/upload-history/pdf/', views.upload_history_pdf, name='upload_history_pdf'),
    path('category/<slug:category>/order/', views.order_create, name='order_create'),
    path('category/<slug:category>/order-history/', views.order_list, name='order_list'),
    path('category/<slug:category>/order-history/pdf/', views.order_history_pdf, name='order_history_pdf'),
    path('order/<int:pk>/fulfill/', views.order_fulfill, name='order_fulfill'),
    path('order/<int:pk>/disclosed/', views.order_mark_disclosed, name='order_mark_disclosed'),
    path('category/<slug:category>/history/', views.issue_history, name='issue_history'),
    path('category/<slug:category>/history/pdf/', views.issue_history_pdf, name='issue_history_pdf'),
    path('profile/', views.profile, name='profile'),
    path('profile/settings/', views.change_password, name='change_password'),
    path('profile/add-user/', views.add_user, name='add_user'),
    path('reports/logins/', views.reports_logins, name='reports_logins'),
    path('reports/logins/pdf/', views.reports_logins_pdf, name='reports_logins_pdf'),
    path('reports/transactions/', views.reports_transactions, name='reports_transactions'),
    path('reports/transactions/pdf/', views.reports_transactions_pdf, name='reports_transactions_pdf'),
    path('reports/updates/', views.reports_updates, name='reports_updates'),
    path('reports/updates/pdf/', views.reports_updates_pdf, name='reports_updates_pdf'),
]
