# Generated by Django 5.2.12 on 2026-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='approval_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='approved_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='request_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='managementuploadrequest',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='management_receipts/'),
        ),
        migrations.AddField(
            model_name='managementuploadrequest',
            name='receipt_file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
