# Generated by Django 5.2.12 on 2026-03-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_managementuploadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='cabin_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rack',
            name='number_of_racks',
            field=models.PositiveIntegerField(default=1, help_text='Number of racks in this cabin/setup'),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issue completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
