# Generated by Django 5.2.12 on 2026-03-10 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_login_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('networking', 'Networking'), ('hardware', 'Hardware'), ('security', 'Security'), ('server_parts', 'Server Parts')], db_index=True, max_length=20)),
                ('cabin_name', models.CharField(blank=True, default='', max_length=100)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('column_number', models.PositiveIntegerField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('dimension', 'Dimensions')], default='', max_length=20)),
                ('measurement_value', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.TextField(blank=True, default='')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deleted history',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
