# Generated by Django 5.2.12 on 2026-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rack_cabin_name_rack_number_of_racks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementuploadrequest',
            name='request_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
