# Generated by Django 5.2.12 on 2026-03-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_lan',
            field=models.BooleanField(default=False, help_text='Whether the login was from a LAN/private IP address'),
        ),
    ]
