# Generated by Django 5.2.12 on 2026-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_loginhistory_is_lan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='hostname',
            field=models.CharField(blank=True, default='', help_text='System hostname resolved from IP address', max_length=255),
        ),
    ]
