# Generated by Django 5.2.12 on 2026-03-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_loginhistory_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='request_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
