# Generated by Django 5.2.12 on 2026-03-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_issuerequest_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
