# Generated by Django 5.2.12 on 2026-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='approved_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin section that approved this issue', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='issued_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin section that issued this item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='approved_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin section that approved this request', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='issued_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin section that issued this item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='rejected_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin section that rejected this request', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR Department'), ('finance', 'Finance Department'), ('it', 'IT Department'), ('operations', 'Operations'), ('management', 'Management'), ('procurement', 'Procurement'), ('maintenance', 'Maintenance'), ('security', 'Security Department')], help_text='Admin department section (only for Stage 1 users)', max_length=20, null=True),
        ),
    ]
