# Generated by Django 5.2.12 on 2026-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_issuehistory_approved_by_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('technical', 'Technical'), ('operations', 'Operations'), ('support', 'Support')], help_text='Admin department (only for Stage 1 users)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='approved_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section that approved this issue', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='issued_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section that issued this item', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='approved_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section that approved this request', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='issued_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section that issued this item', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='rejected_by_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section that rejected this request', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_section',
            field=models.CharField(blank=True, choices=[('hr', 'HR'), ('finance', 'Finance'), ('management', 'Management'), ('procurement', 'Procurement'), ('it', 'IT Support'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('logistics', 'Logistics'), ('maintenance', 'Maintenance'), ('quality', 'Quality Control'), ('production', 'Production'), ('customer_service', 'Customer Service'), ('helpdesk', 'Helpdesk'), ('training', 'Training'), ('documentation', 'Documentation')], help_text='Admin section (only for Stage 1 users)', max_length=20, null=True),
        ),
    ]
