# Generated by Django 5.2.12 on 2026-03-17 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_issuehistory_approved_by_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='approved_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Admin department that approved this issue', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='confirmed_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Department of user who confirmed receipt', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='confirmed_by_section',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa ', 'QA'), ('ga', 'GA'), ('facility', 'Facility'), ('common', 'Common'), ('customer Quality Support', 'Customer Quality Support'), ('customs', 'Customs'), ('nPI', 'NPI'), ('shipping and Logistics', 'Shipping and Logistics'), ('common', 'Common'), ('costing', 'Costing'), ('general A/c', 'General A/c'), ('management Accounting', 'Management Accounting'), ('common', 'Common'), ('core shop', 'Core shop'), ('ie', 'IE'), ('maintenance', 'Maintenance'), ('melting', 'Melting'), ('molding', 'Molding'), ('post treatment', 'Post treatment'), ('production planning', 'Production Planning'), ('quality control', 'Quality Control'), ('sand factory', 'Sand Factory'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('security office', 'Security Office'), ('hse', 'HSE'), ('ohc', 'OHC'), ('common', 'Common'), ('employee engagement', 'Employee Engagement'), ('industrial relation', 'Industrial Relation'), ('payroll', 'Payroll'), ('training and development', 'Training and Development'), ('it-tools', 'IT-Tools'), ('automation', 'Automation'), ('epcp', 'EPCP'), ('fixture maintenance', 'Fixture Maintenance'), ('general / office', 'General / Office'), ('general affaires', 'General Affaires'), ('machining1', 'Machining1'), ('machining2', 'Machining2'), ('machining3-sec1', 'Machining3-Sec1'), ('machining3-sec2', 'Machining3-Sec2'), ('maintenance', 'Maintenance'), ('post machining2', 'Post Machining2'), ('post machining3-sec1', 'Post Machining3-Sec1'), ('post machining3-sec2', 'Post Machining3-Sec2'), ('production planning', 'Production Planning'), ('qc support', 'QC Support'), ('quality control2', 'Quality Control2'), ('quality control3-sec1', 'Quality Control3-Sec1'), ('quality control3-sec2', 'Quality Control3-Sec2'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('purchase', 'Purchase'), ('warehouse', 'Warehouse'), ('common', 'Common'), ('material control', 'Material Control'), ('production control', 'Production Control'), ('calibration', 'Calibration'), ('common', 'Common'), ('iso', 'ISO'), ('mis', 'MIS')], help_text='Section of user who confirmed receipt', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issuehistory',
            name='issued_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Admin department that issued this item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='approved_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Admin department that approved this request', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_requests_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='confirmed_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Department of user who confirmed receipt', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='confirmed_by_section',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa ', 'QA'), ('ga', 'GA'), ('facility', 'Facility'), ('common', 'Common'), ('customer Quality Support', 'Customer Quality Support'), ('customs', 'Customs'), ('nPI', 'NPI'), ('shipping and Logistics', 'Shipping and Logistics'), ('common', 'Common'), ('costing', 'Costing'), ('general A/c', 'General A/c'), ('management Accounting', 'Management Accounting'), ('common', 'Common'), ('core shop', 'Core shop'), ('ie', 'IE'), ('maintenance', 'Maintenance'), ('melting', 'Melting'), ('molding', 'Molding'), ('post treatment', 'Post treatment'), ('production planning', 'Production Planning'), ('quality control', 'Quality Control'), ('sand factory', 'Sand Factory'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('security office', 'Security Office'), ('hse', 'HSE'), ('ohc', 'OHC'), ('common', 'Common'), ('employee engagement', 'Employee Engagement'), ('industrial relation', 'Industrial Relation'), ('payroll', 'Payroll'), ('training and development', 'Training and Development'), ('it-tools', 'IT-Tools'), ('automation', 'Automation'), ('epcp', 'EPCP'), ('fixture maintenance', 'Fixture Maintenance'), ('general / office', 'General / Office'), ('general affaires', 'General Affaires'), ('machining1', 'Machining1'), ('machining2', 'Machining2'), ('machining3-sec1', 'Machining3-Sec1'), ('machining3-sec2', 'Machining3-Sec2'), ('maintenance', 'Maintenance'), ('post machining2', 'Post Machining2'), ('post machining3-sec1', 'Post Machining3-Sec1'), ('post machining3-sec2', 'Post Machining3-Sec2'), ('production planning', 'Production Planning'), ('qc support', 'QC Support'), ('quality control2', 'Quality Control2'), ('quality control3-sec1', 'Quality Control3-Sec1'), ('quality control3-sec2', 'Quality Control3-Sec2'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('purchase', 'Purchase'), ('warehouse', 'Warehouse'), ('common', 'Common'), ('material control', 'Material Control'), ('production control', 'Production Control'), ('calibration', 'Calibration'), ('common', 'Common'), ('iso', 'ISO'), ('mis', 'MIS')], help_text='Section of user who confirmed receipt', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='issued_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Admin department that issued this item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='rejected_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Admin department that rejected this request', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='requested_by_department',
            field=models.CharField(blank=True, choices=[('admin', 'Administration'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa', 'QA')], help_text='Department of the user who made this request', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='requested_by_section',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('business', 'Business'), ('finance', 'Finance'), ('foundary', 'Foundary'), ('gm office', 'GM Office'), ('hr', 'HR'), ('hse', 'HSE'), ('it', 'IT'), ('material', 'Material'), ('ms', 'MS'), ('pmc', 'PMC'), ('qa ', 'QA'), ('ga', 'GA'), ('facility', 'Facility'), ('common', 'Common'), ('customer Quality Support', 'Customer Quality Support'), ('customs', 'Customs'), ('nPI', 'NPI'), ('shipping and Logistics', 'Shipping and Logistics'), ('common', 'Common'), ('costing', 'Costing'), ('general A/c', 'General A/c'), ('management Accounting', 'Management Accounting'), ('common', 'Common'), ('core shop', 'Core shop'), ('ie', 'IE'), ('maintenance', 'Maintenance'), ('melting', 'Melting'), ('molding', 'Molding'), ('post treatment', 'Post treatment'), ('production planning', 'Production Planning'), ('quality control', 'Quality Control'), ('sand factory', 'Sand Factory'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('security office', 'Security Office'), ('hse', 'HSE'), ('ohc', 'OHC'), ('common', 'Common'), ('employee engagement', 'Employee Engagement'), ('industrial relation', 'Industrial Relation'), ('payroll', 'Payroll'), ('training and development', 'Training and Development'), ('it-tools', 'IT-Tools'), ('automation', 'Automation'), ('epcp', 'EPCP'), ('fixture maintenance', 'Fixture Maintenance'), ('general / office', 'General / Office'), ('general affaires', 'General Affaires'), ('machining1', 'Machining1'), ('machining2', 'Machining2'), ('machining3-sec1', 'Machining3-Sec1'), ('machining3-sec2', 'Machining3-Sec2'), ('maintenance', 'Maintenance'), ('post machining2', 'Post Machining2'), ('post machining3-sec1', 'Post Machining3-Sec1'), ('post machining3-sec2', 'Post Machining3-Sec2'), ('production planning', 'Production Planning'), ('qc support', 'QC Support'), ('quality control2', 'Quality Control2'), ('quality control3-sec1', 'Quality Control3-Sec1'), ('quality control3-sec2', 'Quality Control3-Sec2'), ('technical', 'Technical'), ('tooling', 'Tooling'), ('common', 'Common'), ('purchase', 'Purchase'), ('warehouse', 'Warehouse'), ('common', 'Common'), ('material control', 'Material Control'), ('production control', 'Production Control'), ('calibration', 'Calibration'), ('common', 'Common'), ('iso', 'ISO'), ('mis', 'MIS')], help_text='Section of the user who made this request', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('confirmed', 'Confirmed')], db_index=True, default='pending', max_length=20),
        ),
    ]
