# Generated by Django 5.2.12 on 2026-03-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_user_department_section_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
    ]
