# Generated by Django 5.2.12 on 2026-03-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_peripheralapplication_and_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('new_item', 'New Item Added'), ('purchase_received', 'Purchase Received'), ('manual_update', 'Manual Update'), ('quantity_change', 'Quantity Changed')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='inventory.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update History',
                'verbose_name_plural': 'Update History',
                'ordering': ['-updated_at'],
            },
        ),
    ]
