# Generated by Django 5.2.12 on 2026-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0020_alter_user_admin_department_alter_user_admin_section_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='inventory_c_slug_9e1826_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['asset_id'], name='inventory_d_asset_i_259773_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['category'], name='inventory_d_categor_5fe926_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['deleted_by'], name='inventory_d_deleted_bb43a7_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['deleted_at'], name='inventory_d_deleted_1af0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['deleted_by', 'deleted_at'], name='inventory_d_deleted_b9163f_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedhistory',
            index=models.Index(fields=['category', 'deleted_at'], name='inventory_d_categor_18e191_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['product'], name='inventory_i_product_ff9e14_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['issued_by'], name='inventory_i_issued__bf490f_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['approved_by'], name='inventory_i_approve_e8f439_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['confirmed_by'], name='inventory_i_confirm_87a10a_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['receiver'], name='inventory_i_receive_5d152c_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['issued_at'], name='inventory_i_issued__41eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['product', 'issued_at'], name='inventory_i_product_b3fa16_idx'),
        ),
        migrations.AddIndex(
            model_name='issuehistory',
            index=models.Index(fields=['issued_by', 'issued_at'], name='inventory_i_issued__f5e24e_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['request_id'], name='inventory_i_request_f3a684_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['product'], name='inventory_i_product_d7bb09_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['requested_by'], name='inventory_i_request_b00e00_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['status'], name='inventory_i_status_5fc28b_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['created_at'], name='inventory_i_created_13738a_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['updated_at'], name='inventory_i_updated_210155_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['status', 'created_at'], name='inventory_i_status_c4f803_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['requested_by', 'status'], name='inventory_i_request_850d60_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerequest',
            index=models.Index(fields=['product', 'status'], name='inventory_i_product_81f076_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user'], name='inventory_l_user_id_9c7dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['logged_in_at'], name='inventory_l_logged__41ea57_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['ip_address'], name='inventory_l_ip_addr_d3c221_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['is_lan'], name='inventory_l_is_lan_60dc45_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'logged_in_at'], name='inventory_l_user_id_e9f447_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['logged_in_at', 'is_lan'], name='inventory_l_logged__61b8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product'], name='inventory_o_product_a2e90c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['requested_by'], name='inventory_o_request_2c09df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='inventory_o_status_66c9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='inventory_o_created_60ea1c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['updated_at'], name='inventory_o_updated_5dfdef_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='inventory_o_status_64129c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', 'status'], name='inventory_o_product_483c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['requested_by', 'status'], name='inventory_o_request_877a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheralapplication',
            index=models.Index(fields=['form_id'], name='inventory_p_form_id_e4ca30_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheralapplication',
            index=models.Index(fields=['created_by'], name='inventory_p_created_f481e4_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheralapplication',
            index=models.Index(fields=['created_at'], name='inventory_p_created_8828af_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheralapplication',
            index=models.Index(fields=['employee_id'], name='inventory_p_employe_8b61da_idx'),
        ),
        migrations.AddIndex(
            model_name='peripheralapplication',
            index=models.Index(fields=['equipment_name'], name='inventory_p_equipme_ffc949_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['asset_id'], name='inventory_p_asset_i_02f271_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_name'], name='inventory_p_item_na_dca1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rack'], name='inventory_p_rack_id_93d241_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity_available'], name='inventory_p_quantit_0fdd49_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_at'], name='inventory_p_updated_ec265f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'asset_id'], name='inventory_p_categor_444d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'rack'], name='inventory_p_categor_97da98_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['category'], name='inventory_r_categor_135e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['cabin_name'], name='inventory_r_cabin_n_3ea552_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['rack_number'], name='inventory_r_rack_nu_5dee5b_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['created_at'], name='inventory_r_created_50b9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['product'], name='inventory_u_product_9d9946_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['uploaded_by'], name='inventory_u_uploade_24f329_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['uploaded_at'], name='inventory_u_uploade_5801ff_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['product', 'uploaded_at'], name='inventory_u_product_c8ef51_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadhistory',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='inventory_u_uploade_2b7c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='inventory_u_usernam_93259e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='inventory_u_email_ef5347_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stage'], name='inventory_u_stage_63c612_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='inventory_u_departm_870f92_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['admin_department'], name='inventory_u_admin_d_ddf87f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='inventory_u_is_acti_7eebae_idx'),
        ),
    ]
