# Generated by Django 5.2.12 on 2026-04-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_category_inventory_c_slug_9e1826_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerequest',
            name='requested_id',
        ),
    ]
