# Generated by Django 5.2.12 on 2026-04-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_issuerequest_requested_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['rack_number']},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('rack_number', 'cabin_name')},
        ),
        migrations.RemoveField(
            model_name='rack',
            name='category',
        ),
    ]
