# Generated by Django 5.2.12 on 2026-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_rack_options_alter_rack_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/'),
        ),
    ]
