# Generated by Django 5.2.12 on 2026-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_order_requested_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requested_file',
        ),
        migrations.AddField(
            model_name='managementuploadrequest',
            name='material_upload_form',
            field=models.FileField(blank=True, null=True, upload_to='material_upload_forms/'),
        ),
    ]
