# Generated by Django 5.2.12 on 2026-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_order_requested_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asset_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
