# Generated by Django 5.2.12 on 2026-04-14 17:30

from django.db import migrations


def update_asset_ids_to_gtiit(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    
    # Get all products ordered by created_at to maintain some order
    products = Product.objects.all().order_by('created_at')
    
    # Update each product with a GTIIT ID
    for index, product in enumerate(products, start=1):
        # Only update if not already in GTIIT format
        if not product.asset_id.startswith('GTIIT'):
            product.asset_id = f'GTIIT{index}'
            product.save(update_fields=['asset_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_product_asset_id'),
    ]

    operations = [
        migrations.RunPython(update_asset_ids_to_gtiit),
    ]
