# Generated by Django 5.2.12 on 2026-04-15 09:50

from django.db import migrations


def populate_requested_by_username(apps, schema_editor):
    IssueRequest = apps.get_model('inventory', 'IssueRequest')
    User = apps.get_model('inventory', 'User')
    
    # Populate requested_by_username for existing records
    for ir in IssueRequest.objects.filter(requested_by_username=''):
        if ir.requested_by:
            ir.requested_by_username = ir.requested_by.username
            ir.save(update_fields=['requested_by_username'])
        # For records without requested_by, try to extract username from full_name or leave empty
        # We can't reliably extract username from full_name, so we'll leave them empty
        # New records created with the new form will have username populated


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_issuerequest_requested_by_username_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_requested_by_username, migrations.RunPython.noop),
    ]
