# Generated by Django 5.2.12 on 2026-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_userstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstagehistory',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userstagehistory',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
