# Generated by Django 5.2.12 on 2026-04-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_userstagehistory_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='request_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='permanent', help_text='Type of request: permanent or temporary', max_length=20),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='return_date',
            field=models.DateField(blank=True, help_text='Expected return date for temporary requests', null=True),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='return_location',
            field=models.CharField(blank=True, choices=[('store', 'Store'), ('cabin', 'Cabin'), ('other', 'Other')], default='', help_text='Location where item should be returned', max_length=50),
        ),
    ]
