# Generated by Django 5.2.12 on 2026-04-15 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_issuerequest_request_type_issuerequest_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='issuerequest',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='issuerequest',
            name='return_location',
        ),
        migrations.CreateModel(
            name='TemporaryItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('return_date', models.DateField(help_text='Expected return date')),
                ('return_location', models.CharField(choices=[('store', 'Store'), ('cabin', 'Cabin'), ('other', 'Other')], default='store', max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned')], default='issued', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_items_issued', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_items_received', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_history', to='inventory.product')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
