# Generated by Django 5.2.12 on 2026-04-15 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_remove_issuerequest_request_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryitemhistory',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='temporaryitemhistory',
            name='return_location',
        ),
        migrations.AddField(
            model_name='temporaryitemhistory',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_items_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
