# Generated by Django 5.2.12 on 2026-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_temporaryitemhistory_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryitemhistory',
            name='request_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
