# Generated by Django 5.2.12 on 2026-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_temporaryitemhistory_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryitemhistory',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
