# Generated by Django 5.2.12 on 2026-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_temporaryitemhistory_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuerequest',
            name='needs_confirmation',
            field=models.BooleanField(default=False, help_text='Whether the user needs to confirm receipt of the item'),
        ),
    ]
