# Generated by Django 5.2.12 on 2026-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_returneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryitemhistory',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Username of the person the item is issued to', max_length=100),
        ),
    ]
