# Generated by Django 5.2.12 on 2026-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_temporaryitemhistory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryitemhistory',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Full name of the person the item is issued to', max_length=200),
        ),
    ]
