# Generated by Django 5.2.12 on 2026-04-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_temporaryitemhistory_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='receiver_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
