# Generated by Django 5.2.12 on 2026-04-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_issuehistory_receiver_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseModificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(choices=[('add', 'Add'), ('subtract', 'Subtract')], max_length=10)),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('material_upload_form', models.FileField(blank=True, null=True, upload_to='material_upload_forms_history/')),
                ('notes', models.TextField(blank=True, default='')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_modifications', to=settings.AUTH_USER_MODEL)),
                ('upload_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='inventory.managementuploadrequest')),
            ],
            options={
                'verbose_name_plural': 'Purchase modification history',
                'ordering': ['-modified_at'],
            },
        ),
    ]
