# Generated by Django 5.2.12 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_product_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='quantity_added',
            field=models.IntegerField(),
        ),
    ]
