# Generated by Django 5.2.12 on 2026-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_uploadhistory_quantity_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returneditem',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
